### ISSUE TITLE
NLP::sentiment issue

### ISSUE THREAD

**Issue by vinay-kaklotar** [web64/laravel-nlp#1]
I got this error while run the 
`$sentiment = NLP::sentiment("This is great!");`

> Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP)

**Comment by web64** [comment]
Thanks for reporting this!

This was caused by debug/error messages written to STDOUT. I only used this package on the command line so I never noticed the problem when running on a web server.

I published an update, so if you run `composer update` you should have a working version.
Alternatively, disable debugging to hide the debug/error messages, in the `nlp.php` config file.
```php
    'debug' => false,
```

Cheers,
Olav
